[package]
name = "valheim-asm"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/imkiva/valheim"
description = "RISC-V instructions and assembler"
license = "MIT"

[dependencies]
modular-bitfield = "0.11.2"
bytebuffer = "2.0.1"
