[alias]
xtask = "run --release --package xtask --"
start = "run --release --package valheim-cli --"
make = "build --release --package valheim-cli --"
make-debug = "build --package valheim-cli --"
test = "xtask test"
