use crate::cpu::{PrivilegeMode, RV64Cpu};
use crate::cpu::csr::CSRMap::{MCAUSE, MEDELEG, MEIP_MASK, MEPC, MIDELEG, MIE, MIP, MSIP_MASK, MTIP_MASK, MTVAL, MTVEC, SCAUSE, SEIP_MASK, SEPC, SSIP_MASK, STIP_MASK, STVAL, STVEC};
use crate::memory::VirtAddr;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IRQ {
  /// Machine external IRQ
  MEI,
  /// Machine software IRQ
  MSI,
  /// Machine timer IRQ
  MTI,
  /// Supervisor external IRQ
  SEI,
  /// Supervisor software IRQ
  SSI,
  /// Supervisor timer IRQ
  STI,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Exception {
  InstructionAddressMisaligned(VirtAddr),
  InstructionAccessFault(VirtAddr),
  IllegalInstruction,
  LoadAccessFault(VirtAddr),
  StoreAccessFault(VirtAddr),
  LoadAddressMisaligned(VirtAddr),
  StoreAddressMisaligned(VirtAddr),
  InstructionPageFault(VirtAddr),
  LoadPageFault(VirtAddr),
  StorePageFault(VirtAddr),
  UserEcall,
  SupervisorEcall,
  MachineEcall,
  Breakpoint,
}

impl RV64Cpu {
  fn interrupt_globally_enabled(&self, interrupt_mask: u64) -> bool {
    let delegated = self.csrs.read_unchecked(MIDELEG) & interrupt_mask != 0;
    match self.mode {
      // A delegated interrupt remains pending while M-mode is running; it cannot trap downward.
      PrivilegeMode::Machine => !delegated && self.csrs.read_mstatus_MIE(),
      // Non-delegated interrupts target the higher M-mode and are therefore globally enabled
      // regardless of SIE. Delegated interrupts target the current S-mode and must honor SIE.
      PrivilegeMode::Supervisor => !delegated || self.csrs.read_sstatus_SIE(),
      // Every implemented interrupt target is more privileged than U-mode.
      PrivilegeMode::User => true,
    }
  }

  pub fn pending_interrupt(&mut self) -> Option<IRQ> {
    self.refresh_local_interrupts();

    // Queue service is device progress, not interrupt delivery. It must continue while global
    // interrupt enables are clear; otherwise a guest can deadlock after submitting block I/O in
    // a critical section. DMA writes invalidate every LR/SC reservation conservatively because
    // reservations currently store guest virtual addresses and may alias the physical target.
    let virtio = self.bus.service_virtio();
    if virtio.dma_write {
      self.reserved.clear();
    }

    // 3.1.6.1 Privilege and Global Interrupt-Enable Stack in mstatus register
    // Global interrupt-enable bits, MIE and SIE, are provided for M-mode and S-mode respectively.
    // When a hart is executing in privilege mode x, interrupts are globally enabled
    // when xIE=1 and globally disabled when xIE=0.
    // Interrupts for lower-privilege modes, w<x, are always globally disabled
    // regardless of the setting of any global wIE bit for the lower-privilege mode.
    // Interrupts for higher-privilege modes, y>x, are always globally enabled
    // regardless of the setting of the global yIE bit for the higher-privilege mode.

    // Higher-privilege-level code can use separate per-interrupt enable bits
    // to disable selected higher-privilege-mode interrupts before ceding control
    // to a lower-privilege mode.

    // 3.3.3 Wait for Interrupt
    // The WFI instruction can also be executed when interrupts are disabled.
    // The operation of WFI must be unaffected by the global interrupt bits in mstatus (MIE and SIE)
    // and the delegation register mideleg (i.e., the hart must resume if a locally enabled interrupt
    // becomes pending, even if it has been delegated to a less-privileged mode),
    // but should honor the individual interrupt enables (e.g, MTIE) (i.e., implementations should
    // avoid resuming the hart if the interrupt is pending but not individually enabled).
    // WFI is also required to resume execution for locally enabled interrupts pending at any privilege level,
    // regardless of the global interrupt enable at each privilege level.

    // 3.1.9 Machine Interrupt Registers (mip and mie)
    // The machine-level interrupt fixed-priority ordering rules were developed with the following rationale:
    // 1. Interrupts for higher privilege modes must be serviced before interrupts
    //    for lower privilege modes to support preemption.
    // 2. The platform-specific machine-level interrupt sources in bits 16 and above have
    //    platform-specific priority, but are typically chosen to have the highest service priority
    //    to support very fast local vectored interrupts.
    // 3. External interrupts are handled before internal (timer/software) interrupts
    //    as external interrupts are usually generated by devices that might require
    //    low interrupt service times.
    // 4. Software interrupts are handled before internal timer interrupts, because internal
    //    timer interrupts are usually intended for time slicing, where time precision is less important,
    //    whereas software interrupts are used for inter-processor messaging.
    //    Software interrupts can be avoided when high-precision timing is required,
    //    or high-precision timer interrupts can be routed via a different interrupt path.

    // Pulse-based devices retain their event until polled. Do not consume a second UART pulse
    // while the first is still being handled with SIE clear: the PLIC gateway coalesces requests
    // for an in-service source. A waiting hart must still poll regardless of the global enable.
    // VirtIO is deliberately serviced above this gate because queue progress is not a pulse.
    if self.wfi || self.interrupt_globally_enabled(SEIP_MASK) {
      for dev in self.bus.devices.iter() {
        if let Some(irq_id) = dev.is_interrupting() {
          self.bus.plic.update_pending(irq_id);
        }
      }
    }

    // SEIP is a level presented by S-context 1 of the PLIC, not a one-shot notification. Rebuild
    // it on every interrupt poll so claim, complete, enable, threshold and priority changes are
    // reflected even when no device emits a new event in this round.
    let mip = self.csrs.read_unchecked(MIP);
    let mip = if self.bus.plic.supervisor_irq_pending() {
      mip | SEIP_MASK
    } else {
      mip & !SEIP_MASK
    };
    let _ = self.csrs.write_unchecked(MIP, mip);

    // 3.1.9 Machine Interrupt Registers (mip and mie)
    // Multiple simultaneous interrupts destined for M-mode are handled
    // in the following decreasing priority order: MEI, MSI, MTI, SEI, SSI, STI.

    // only enable bit and pending bit are both set, an interrupt is treated as taken
    let mip = self.csrs.read_unchecked(MIP) & self.csrs.read_unchecked(MIE);

    // fast-path check
    if mip == 0 {
      return None;
    }

    // WFI wakeup and interrupt delivery are separate decisions. A locally enabled pending
    // interrupt resumes a waiting hart regardless of global enables and delegation. Delivery is
    // then decided per candidate because a higher-privilege interrupt is globally enabled even if
    // the current lower privilege has disabled its own interrupts.
    if self.wfi {
      self.wfi = false;
    }

    let candidates = [
      (MEIP_MASK, IRQ::MEI),
      (MSIP_MASK, IRQ::MSI),
      (MTIP_MASK, IRQ::MTI),
      (SEIP_MASK, IRQ::SEI),
      (SSIP_MASK, IRQ::SSI),
      (STIP_MASK, IRQ::STI),
    ];
    for (mask, irq) in candidates {
      if mip & mask != 0 && self.interrupt_globally_enabled(mask) {
        let _ = self.csrs.write_unchecked(MIP, self.csrs.read_unchecked(MIP) & !mask);
        return Some(irq);
      }
    }

    None
  }
}

#[cfg(test)]
mod tests {
  use std::collections::VecDeque;
  use std::io;

  use memmap2::MmapMut;

  use super::{IRQ, RV64Cpu};
  use crate::cpu::bus::{PLIC_BASE, VIRTIO_BASE, VIRTIO_NET_BASE};
  use crate::cpu::csr::CSRMap::{
    MCAUSE, MEPC, MIDELEG, MIE, MIP, MTIE_MASK, MTIP_MASK, MTVEC, STIE_MASK, STIP_MASK,
  };
  use crate::cpu::PrivilegeMode;
  use crate::device::virtio::{EthernetBackend, VIRTIO_NET_IRQ};
  use crate::memory::VirtAddr;

  struct ReceiveBackend {
    frames: VecDeque<Vec<u8>>,
  }

  impl EthernetBackend for ReceiveBackend {
    fn try_send(&mut self, _frame: &[u8]) -> io::Result<bool> {
      Ok(true)
    }

    fn try_recv(&mut self) -> io::Result<Option<Vec<u8>>> {
      Ok(self.frames.pop_front())
    }

    fn shutdown(&mut self) -> io::Result<()> {
      Ok(())
    }
  }

  fn waiting_cpu_with_timer_interrupt(
    individually_enabled: bool,
    globally_enabled: bool,
  ) -> RV64Cpu {
    let mut cpu = RV64Cpu::new(None);
    cpu.wfi = true;
    cpu.write_pc(VirtAddr(0x8000_0000));
    cpu.csrs.write_unchecked(MTVEC, 0x8000_0100).unwrap();
    cpu.csrs
      .write_unchecked(MIE, if individually_enabled { MTIE_MASK } else { 0 })
      .unwrap();
    cpu.csrs.write_unchecked(MIP, MTIP_MASK).unwrap();
    cpu.csrs.write_mstatus_MIE(globally_enabled);
    cpu
  }

  #[test]
  fn locally_enabled_interrupt_wakes_wfi_without_global_enable_or_trap() {
    let mut cpu = waiting_cpu_with_timer_interrupt(true, false);

    assert_eq!(cpu.pending_interrupt(), None);
    assert!(!cpu.wfi);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & MTIP_MASK, MTIP_MASK);
    assert_eq!(cpu.read_pc(), VirtAddr(0x8000_0000));
    assert_eq!(cpu.csrs.read_unchecked(MCAUSE), 0);

    cpu.csrs.write_mstatus_MIE(true);
    let irq = cpu.pending_interrupt().unwrap();
    assert_eq!(irq, IRQ::MTI);
    irq.handle(&mut cpu).unwrap();
    assert_eq!(cpu.read_pc(), VirtAddr(0x8000_0100));
    assert_eq!(cpu.csrs.read_unchecked(MEPC), 0x8000_0000);
    assert_eq!(cpu.csrs.read_unchecked(MCAUSE), (1_u64 << 63) | 7);
  }

  #[test]
  fn globally_and_locally_enabled_interrupt_wakes_wfi_and_is_delivered() {
    let mut cpu = waiting_cpu_with_timer_interrupt(true, true);

    let irq = cpu.pending_interrupt().unwrap();
    assert_eq!(irq, IRQ::MTI);
    irq.handle(&mut cpu).unwrap();
    assert!(!cpu.wfi);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & MTIP_MASK, 0);
    assert_eq!(cpu.read_pc(), VirtAddr(0x8000_0100));
    assert_eq!(cpu.csrs.read_unchecked(MEPC), 0x8000_0000);
    assert_eq!(cpu.csrs.read_unchecked(MCAUSE), (1_u64 << 63) | 7);
  }

  #[test]
  fn individually_disabled_interrupt_does_not_wake_wfi() {
    let mut cpu = waiting_cpu_with_timer_interrupt(false, true);

    assert_eq!(cpu.pending_interrupt(), None);
    assert!(cpu.wfi);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & MTIP_MASK, MTIP_MASK);
  }

  #[test]
  fn machine_timer_preempts_supervisor_even_when_sie_is_clear() {
    let mut cpu = waiting_cpu_with_timer_interrupt(true, false);
    cpu.mode = PrivilegeMode::Supervisor;

    let irq = cpu.pending_interrupt().unwrap();
    assert_eq!(irq, IRQ::MTI);
    assert!(!cpu.wfi);
    irq.handle(&mut cpu).unwrap();
    assert_eq!(cpu.mode, PrivilegeMode::Machine);
    assert_eq!(cpu.read_pc(), VirtAddr(0x8000_0100));
    assert_eq!(cpu.csrs.read_unchecked(MCAUSE), (1_u64 << 63) | 7);
  }

  fn supervisor_with_delegated_timer(waiting: bool) -> RV64Cpu {
    let mut cpu = RV64Cpu::new(None);
    cpu.mode = PrivilegeMode::Supervisor;
    cpu.wfi = waiting;
    cpu.csrs.write_unchecked(MIDELEG, STIP_MASK).unwrap();
    cpu.csrs.write_unchecked(MIE, STIE_MASK).unwrap();
    cpu.csrs.write_unchecked(MIP, STIP_MASK).unwrap();
    cpu.csrs.write_sstatus_SIE(false);
    cpu
  }

  #[test]
  fn delegated_supervisor_timer_honors_sie_outside_wfi() {
    let mut cpu = supervisor_with_delegated_timer(false);

    assert_eq!(cpu.pending_interrupt(), None);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & STIP_MASK, STIP_MASK);
  }

  #[test]
  fn delegated_supervisor_timer_wakes_wfi_without_trapping_when_sie_is_clear() {
    let mut cpu = supervisor_with_delegated_timer(true);

    assert_eq!(cpu.pending_interrupt(), None);
    assert!(!cpu.wfi);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & STIP_MASK, STIP_MASK);
  }

  #[test]
  fn delegated_supervisor_timer_cannot_interrupt_machine_mode() {
    let mut cpu = supervisor_with_delegated_timer(false);
    cpu.mode = PrivilegeMode::Machine;
    cpu.csrs.write_mstatus_MIE(true);

    assert_eq!(cpu.pending_interrupt(), None);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & STIP_MASK, STIP_MASK);
  }

  #[test]
  fn seip_tracks_plic_claimable_state_each_round() {
    use crate::cpu::bus::PLIC_BASE;
    use crate::cpu::csr::CSRMap::SEIP_MASK;

    const IRQ: u64 = 1;
    const S_ENABLE: u64 = PLIC_BASE + 0x2080;
    const S_CLAIM: u64 = PLIC_BASE + 0x201004;

    let mut cpu = RV64Cpu::new(None);
    cpu.bus
      .plic
      .write(VirtAddr(PLIC_BASE + IRQ * 4), 1)
      .unwrap();
    cpu.bus
      .plic
      .write(VirtAddr(S_ENABLE), 1 << IRQ)
      .unwrap();
    cpu.bus.plic.update_pending(IRQ);

    assert_eq!(cpu.csrs.read_unchecked(MIP) & SEIP_MASK, 0);
    assert_eq!(cpu.pending_interrupt(), None);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & SEIP_MASK, SEIP_MASK);

    assert_eq!(cpu.bus.plic.read(VirtAddr(S_CLAIM)).unwrap(), IRQ as u32);
    assert_eq!(cpu.pending_interrupt(), None);
    assert_eq!(cpu.csrs.read_unchecked(MIP) & SEIP_MASK, 0);
  }

  #[test]
  fn virtio_progress_is_independent_of_global_interrupts_and_invalidates_reservations() {
    const QUEUE_BASE: u64 = 0x8000_1000;
    const AVAIL_BASE: u64 = QUEUE_BASE + 16 * 8;
    const USED_BASE: u64 = 0x8000_2000;
    const HEADER: u64 = 0x8000_4000;
    const STATUS_BYTE: u64 = 0x8000_4100;

    let mut cpu = RV64Cpu::new(None);
    cpu.bus
      .virtio
      .set_image(MmapMut::map_anon(512).unwrap())
      .unwrap();
    cpu.bus
      .plic
      .write(VirtAddr(PLIC_BASE + 4), 1)
      .unwrap();
    cpu.bus
      .plic
      .write(VirtAddr(PLIC_BASE + 0x2080), 1 << 1)
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_BASE + 0x28), 0x1000)
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_BASE + 0x38), 8)
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_BASE + 0x40), (QUEUE_BASE / 0x1000) as u32)
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_BASE + 0x70), 4)
      .unwrap();

    let mut header = [0_u8; 16];
    header[0..4].copy_from_slice(&4_u32.to_le_bytes());
    cpu.bus.mem.write_bytes(VirtAddr(HEADER), &header).unwrap();

    let mut descriptor = [0_u8; 16];
    descriptor[0..8].copy_from_slice(&HEADER.to_le_bytes());
    descriptor[8..12].copy_from_slice(&16_u32.to_le_bytes());
    descriptor[12..14].copy_from_slice(&1_u16.to_le_bytes());
    descriptor[14..16].copy_from_slice(&1_u16.to_le_bytes());
    cpu
      .bus
      .mem
      .write_bytes(VirtAddr(QUEUE_BASE), &descriptor)
      .unwrap();

    descriptor = [0; 16];
    descriptor[0..8].copy_from_slice(&STATUS_BYTE.to_le_bytes());
    descriptor[8..12].copy_from_slice(&1_u32.to_le_bytes());
    descriptor[12..14].copy_from_slice(&2_u16.to_le_bytes());
    cpu
      .bus
      .mem
      .write_bytes(VirtAddr(QUEUE_BASE + 16), &descriptor)
      .unwrap();
    cpu
      .bus
      .mem
      .write_bytes(VirtAddr(AVAIL_BASE + 2), &1_u16.to_le_bytes())
      .unwrap();
    cpu
      .bus
      .mem
      .write_bytes(VirtAddr(AVAIL_BASE + 4), &0_u16.to_le_bytes())
      .unwrap();
    cpu.bus.mem.write::<u8>(VirtAddr(STATUS_BYTE), 0xff).unwrap();

    cpu.reserved.push(VirtAddr(0x8000_5000));
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_BASE + 0x50), 0)
      .unwrap();
    assert_eq!(cpu.pending_interrupt(), None);

    assert!(cpu.reserved.is_empty());
    assert_eq!(cpu.bus.mem.read::<u8>(VirtAddr(STATUS_BYTE)), Some(0));
    assert_eq!(cpu.bus.mem.read::<u16>(VirtAddr(USED_BASE + 2)), Some(1));

    // Claiming marks IRQ 1 in service. The VirtIO ACK must lower the PLIC input immediately,
    // before completion, or the still-high cached level would spuriously re-pend the source.
    let claim = VirtAddr(PLIC_BASE + 0x201004);
    assert_eq!(cpu.bus.plic.read(claim).unwrap(), 1);
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_BASE + 0x64), 1)
      .unwrap();
    cpu.bus.plic.write(claim, 1).unwrap();
    assert!(!cpu.bus.plic.supervisor_irq_pending());
  }

  #[test]
  fn virtio_net_rx_progresses_without_a_kick_and_ack_lowers_irq_two_before_completion() {
    const QUEUE_BASE: u64 = 0x8000_6000;
    const AVAIL_BASE: u64 = QUEUE_BASE + 16 * 8;
    const USED_BASE: u64 = 0x8000_7000;
    const BUFFER: u64 = 0x8000_8000;
    const QUEUE_NUM: u32 = 8;

    let frame = vec![0x5a; 60];
    let mut cpu = RV64Cpu::new(None);
    cpu.bus
      .virtio_net
      .set_backend(ReceiveBackend {
        frames: VecDeque::from([frame.clone()]),
      })
      .unwrap();
    cpu.bus
      .plic
      .write(VirtAddr(PLIC_BASE + VIRTIO_NET_IRQ * 4), 1)
      .unwrap();
    cpu.bus
      .plic
      .write(VirtAddr(PLIC_BASE + 0x2080), 1 << VIRTIO_NET_IRQ)
      .unwrap();

    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_NET_BASE + 0x28), 0x1000)
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_NET_BASE + 0x30), 0)
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_NET_BASE + 0x38), QUEUE_NUM)
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_NET_BASE + 0x3c), 0x1000)
      .unwrap();
    cpu.bus
      .write::<u32>(
        VirtAddr(VIRTIO_NET_BASE + 0x40),
        (QUEUE_BASE / 0x1000) as u32,
      )
      .unwrap();
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_NET_BASE + 0x70), 4)
      .unwrap();

    let mut descriptor = [0_u8; 16];
    descriptor[0..8].copy_from_slice(&BUFFER.to_le_bytes());
    descriptor[8..12].copy_from_slice(&(10_u32 + frame.len() as u32).to_le_bytes());
    descriptor[12..14].copy_from_slice(&2_u16.to_le_bytes());
    cpu.bus
      .mem
      .write_bytes(VirtAddr(QUEUE_BASE), &descriptor)
      .unwrap();
    cpu.bus
      .mem
      .write_bytes(VirtAddr(AVAIL_BASE + 2), &1_u16.to_le_bytes())
      .unwrap();
    cpu.bus
      .mem
      .write_bytes(VirtAddr(AVAIL_BASE + 4), &0_u16.to_le_bytes())
      .unwrap();

    cpu.reserved.push(VirtAddr(0x8000_9000));
    assert_eq!(cpu.pending_interrupt(), None);

    assert!(cpu.reserved.is_empty());
    assert_eq!(cpu.bus.mem.read::<u16>(VirtAddr(USED_BASE + 2)), Some(1));
    assert_eq!(
      cpu.bus.mem.read::<u32>(VirtAddr(USED_BASE + 8)),
      Some((10 + frame.len()) as u32),
    );
    assert_eq!(cpu.bus.mem.slice(VirtAddr(BUFFER), 10), Some(&[0; 10][..]));
    assert_eq!(
      cpu.bus.mem.slice(VirtAddr(BUFFER + 10), frame.len()),
      Some(frame.as_slice()),
    );

    let claim = VirtAddr(PLIC_BASE + 0x201004);
    assert_eq!(cpu.bus.plic.read(claim).unwrap(), VIRTIO_NET_IRQ as u32);
    cpu.bus
      .write::<u32>(VirtAddr(VIRTIO_NET_BASE + 0x64), 1)
      .unwrap();
    cpu.bus
      .plic
      .write(claim, VIRTIO_NET_IRQ as u32)
      .unwrap();
    assert!(!cpu.bus.plic.supervisor_irq_pending());
  }
}

impl IRQ {
  /// Just the corresponding bit in MIP register
  fn mcause(&self) -> u64 {
    match self {
      IRQ::SSI => 1,
      IRQ::MSI => 3,
      IRQ::STI => 5,
      IRQ::MTI => 7,
      IRQ::SEI => 9,
      IRQ::MEI => 11,
    }
  }

  pub fn handle(&self, cpu: &mut RV64Cpu) -> Result<(), ()> {
    trap_entry(self.mcause(), 0, true, cpu)
  }
}

impl Exception {
  pub fn mcause_mtval(&self, cpu: &RV64Cpu) -> (u64, u64) {
    match self {
      Exception::InstructionAddressMisaligned(addr) => (0, addr.0),
      Exception::InstructionAccessFault(addr) => (1, addr.0),
      Exception::IllegalInstruction => (2, cpu.instr),
      Exception::Breakpoint => (3, 0),
      Exception::LoadAddressMisaligned(addr) => (4, addr.0),
      Exception::LoadAccessFault(addr) => (5, addr.0),
      Exception::StoreAddressMisaligned(addr) => (6, addr.0),
      Exception::StoreAccessFault(addr) => (7, addr.0),
      Exception::InstructionPageFault(addr) => (12, addr.0),
      Exception::LoadPageFault(addr) => (13, addr.0),
      Exception::StorePageFault(addr) => (15, addr.0),
      Exception::UserEcall => (8, 0),
      Exception::SupervisorEcall => (9, 0),
      Exception::MachineEcall => (11, 0),
    }
  }

  pub fn handle(&self, cpu: &mut RV64Cpu) -> Result<(), ()> {
    let (mcause, mtval) = self.mcause_mtval(cpu);
    trap_entry(mcause, mtval, false, cpu)
  }
}

pub fn trap_entry(mcause: u64, mtval: u64, is_interrupt: bool, cpu: &mut RV64Cpu) -> Result<(), ()> {
  // clear the wait-for-interrupt flag
  if is_interrupt { cpu.wfi = false; }

  let previous_pc = cpu.regs.pc.0;
  let previous_mode = cpu.mode;
  let interrupt_bit = is_interrupt as u64;

  // 3.1.8 Machine Trap Delegation Registers (medeleg and mideleg)
  // In systems with S-mode, the medeleg and mideleg registers must exist,
  // and setting a bit in medeleg or mideleg will delegate the corresponding trap,
  // when occurring in S-mode or U-mode, to the S-mode trap handler.

  // 3.1.9 Machine Interrupt Registers (mip and mie)
  // An interrupt i will trap to M-mode (causing the privilege mode to change to M-mode) if all of the following are true:
  // (a) either the current privilege mode is M and the MIE bit in the mstatus register is set,
  //     or the current privilege mode has less privilege than M-mode;
  // (b) bit i is set in both mip and mie;
  // (c) if register mideleg exists, bit i is not set in mideleg/medeleg.

  // 4.1.3 Supervisor Interrupt Registers (sip and sie)
  // An interrupt i will trap to S-mode if both of the following are true:
  // (a) either the current privilege mode is S and the SIE bit in the sstatus register is set,
  //     or the current privilege mode has less privilege than S-mode;
  // (b) bit i is set in both sip and sie.

  // note: wo don't need to check the following, since we have
  // already checked it in `RV64Cpu::pending_interrupt`:
  // (a) the MIE bit in mstatus, or the SIE bit in sstatus
  // (b) the bit i in (mip & mie) or (sip & sie)

  // we only need to check: (c) bit i is not set in mideleg/medeleg.
  // note: according to 3.1.8, only interrupts/exceptions that occurred
  // not in M-mode can be delegated.

  let occurred_in_machine = previous_mode == PrivilegeMode::Machine;
  let not_delegated = match is_interrupt {
    true => ((cpu.csrs.read_unchecked(MIDELEG) >> mcause) & 1) == 0,
    false => ((cpu.csrs.read_unchecked(MEDELEG) >> mcause) & 1) == 0,
  };

  let trap_to_machine = occurred_in_machine || (previous_mode <= PrivilegeMode::Machine && not_delegated);

  match trap_to_machine {
    true => {
      // enter machine mode
      cpu.mode = PrivilegeMode::Machine;

      // find the trap-vector offset according to the mode saved in mtvec[1:0]
      // 3.1.7 Machine Trap-Vector Base-Address Register (mtvec)
      // When MODE=Direct, all traps into machine mode cause the pc to be set to the address in the BASE field.
      // When MODE=Vectored, all synchronous exceptions into machine mode cause the pc to be set to the address in the BASE field,
      // whereas interrupts cause the pc to be set to the address in the BASE field plus four times the interrupt cause number.
      // For example, a machine-mode timer interrupt (see Table 3.6 on page 39) causes the pc to be set to BASE+0x1c.
      let mode = cpu.csrs.read_unchecked(MTVEC) & 0b11;
      let offset = match (is_interrupt, mode) {
        (false, _) => 0,        // exceptions all cause the pc to the BASE field
        (true, 0) => 0,         // direct mode
        (true, 1) => 4 * mcause, // vectored mode, here we are handling interrupts
        _ => panic!("invalid machine trap-vector address mode in mtvec[1:0]: {}", mode),
      };

      cpu.regs.pc.0 = ((cpu.csrs.read_unchecked(MTVEC) & !(0b11)) + offset) as u64;

      // 3.1.14 Machine Exception Program Counter (mepc)
      // When a trap is taken into M-mode, mepc is written with the virtual address of the instruction
      // that was interrupted or that encountered the exception. Otherwise, mepc is never written
      // by the implementation, though it may be explicitly written by software.
      // The low bit of mepc (mepc[0]) is always zero.
      let _ = cpu.csrs.write_unchecked(MEPC, previous_pc & !1);

      // 3.1.15 Machine Cause Register (mcause)
      // When a trap is taken into M-mode, mcause is written with a code indicating the event
      // that caused the trap. Otherwise, mcause is never written by the implementation,
      // though it may be explicitly written by software.
      // The Interrupt bit (mcause[63]) in the mcause register is set if the trap was caused by an interrupt.
      // The Exception Code field(mcause[0:62]) contains a code identifying the last exception or interrupt.
      let _ = cpu.csrs.write_unchecked(MCAUSE, interrupt_bit << 63 | mcause);

      // 3.1.16 Machine Trap Value Register (mtval)
      // When a trap is taken into M-mode, mtval is either set to zero or written with exception-specific information
      // to assist software in handling the trap. Otherwise, mtval is never written by the implementation,
      // though it may be explicitly written by software.
      let _ = cpu.csrs.write_unchecked(MTVAL, mtval);

      // set MPIE to MIE
      let mie = cpu.csrs.read_mstatus_MIE();
      cpu.csrs.write_mstatus_MPIE(mie);
      // set MIE to 0 to disable interrupts
      cpu.csrs.write_mstatus_MIE(false);

      // set MPP to previous privileged mode
      cpu.csrs.write_mstatus_MPP(previous_mode);
      Ok(())
    }

    false => {
      // Comments omitted since there's only register differences
      if previous_mode == PrivilegeMode::Machine {
        panic!(
          "Machine trap (int={}, mcause={}, mtval={}, mpp={:?}, mepc={:#x}) cannot be handled in supervisor mode",
          is_interrupt,
          interrupt_bit << 63 | mcause,
          mtval,
          previous_mode,
          previous_pc,
        );
      }

      cpu.mode = PrivilegeMode::Supervisor;
      let mode = cpu.csrs.read_unchecked(STVEC) & 0b11;
      let offset = match (is_interrupt, mode) {
        (false, _) => 0,        // exceptions all cause the pc to the BASE field
        (true, 0) => 0,         // direct mode
        (true, 1) => 4 * mcause, // vectored mode, here we are handling interrupts
        _ => panic!("invalid machine trap-vector address mode in stvec[1:0]: {}", mode),
      };

      cpu.regs.pc.0 = ((cpu.csrs.read_unchecked(STVEC) & (!0b11)) + offset) as u64;
      let _ = cpu.csrs.write_unchecked(SEPC, previous_pc & !1);
      let _ = cpu.csrs.write_unchecked(SCAUSE, interrupt_bit << 63 | mcause);
      let _ = cpu.csrs.write_unchecked(STVAL, mtval);

      // set SPIE to SIE
      let sie = cpu.csrs.read_sstatus_SIE();
      cpu.csrs.write_sstatus_SPIE(sie);
      // set SIE to 0 to disable interrupts
      cpu.csrs.write_sstatus_SIE(false);

      // set SPP to previous privileged mode
      cpu.csrs.write_sstatus_SPP(previous_mode);
      Ok(())
    }
  }
}
