[package]
name = "valheim-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modular-bitfield = "0.11.2"
memmap2 = "0.5.3"
derive_more = "0.99.0"
